// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ImageProcessor.djinni

package com.dicekeys.dicekeys;

import java.util.concurrent.atomic.AtomicBoolean;

public abstract class ImageProcessor {
    public abstract boolean process(byte[] image, int width, int height);

    public abstract byte[] overlay(byte[] image, int width, int height);

    public abstract byte[] augmented(byte[] image, int width, int height);

    public abstract String json();

    public abstract boolean isFinished();

    public abstract byte[] faceImage(int faceIndex, int height, byte[] bytes);

    /**
     * `create()` factory method has to be used to create an instance of the class in Swift/Objective-C/Kotlin/Java
     *
     * For example, in Swift:
     * let wrapper = DKImageProcessor.create()!
     *
     * in Objective-C:
     * DKImageProcessor *wrapper = [DKImageProcessor create];
     */
    public static ImageProcessor create()
    {
        return CppProxy.create();
    }

    private static final class CppProxy extends ImageProcessor
    {
        private final long nativeRef;
        private final AtomicBoolean destroyed = new AtomicBoolean(false);

        private CppProxy(long nativeRef)
        {
            if (nativeRef == 0) throw new RuntimeException("nativeRef is zero");
            this.nativeRef = nativeRef;
        }

        private native void nativeDestroy(long nativeRef);
        public void _djinni_private_destroy()
        {
            boolean destroyed = this.destroyed.getAndSet(true);
            if (!destroyed) nativeDestroy(this.nativeRef);
        }
        protected void finalize() throws java.lang.Throwable
        {
            _djinni_private_destroy();
            super.finalize();
        }

        @Override
        public boolean process(byte[] image, int width, int height)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_process(this.nativeRef, image, width, height);
        }
        private native boolean native_process(long _nativeRef, byte[] image, int width, int height);

        @Override
        public byte[] overlay(byte[] image, int width, int height)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_overlay(this.nativeRef, image, width, height);
        }
        private native byte[] native_overlay(long _nativeRef, byte[] image, int width, int height);

        @Override
        public byte[] augmented(byte[] image, int width, int height)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_augmented(this.nativeRef, image, width, height);
        }
        private native byte[] native_augmented(long _nativeRef, byte[] image, int width, int height);

        @Override
        public String json()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_json(this.nativeRef);
        }
        private native String native_json(long _nativeRef);

        @Override
        public boolean isFinished()
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_isFinished(this.nativeRef);
        }
        private native boolean native_isFinished(long _nativeRef);

        @Override
        public byte[] faceImage(int faceIndex, int height, byte[] bytes)
        {
            assert !this.destroyed.get() : "trying to use a destroyed object";
            return native_faceImage(this.nativeRef, faceIndex, height, bytes);
        }
        private native byte[] native_faceImage(long _nativeRef, int faceIndex, int height, byte[] bytes);

        public static native ImageProcessor create();
    }
}
