// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DiceKeyImageProcessorWrapper.djinni

#pragma once

#include "DiceKeyImageProcessorWrapper.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeDiceKeyImageProcessorWrapper final : ::djinni::JniInterface<::dicekeys::DiceKeyImageProcessorWrapper, NativeDiceKeyImageProcessorWrapper> {
public:
    using CppType = std::shared_ptr<::dicekeys::DiceKeyImageProcessorWrapper>;
    using CppOptType = std::shared_ptr<::dicekeys::DiceKeyImageProcessorWrapper>;
    using JniType = jobject;

    using Boxed = NativeDiceKeyImageProcessorWrapper;

    ~NativeDiceKeyImageProcessorWrapper();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeDiceKeyImageProcessorWrapper>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeDiceKeyImageProcessorWrapper>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeDiceKeyImageProcessorWrapper();
    friend ::djinni::JniClass<NativeDiceKeyImageProcessorWrapper>;
    friend ::djinni::JniInterface<::dicekeys::DiceKeyImageProcessorWrapper, NativeDiceKeyImageProcessorWrapper>;

};

}  // namespace djinni_generated
