// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from app.djinni

#pragma once

#include "App.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeApp final : ::djinni::JniInterface<::dicekeys::App, NativeApp> {
public:
    using CppType = std::shared_ptr<::dicekeys::App>;
    using CppOptType = std::shared_ptr<::dicekeys::App>;
    using JniType = jobject;

    using Boxed = NativeApp;

    ~NativeApp();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeApp>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeApp>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeApp();
    friend ::djinni::JniClass<NativeApp>;
    friend ::djinni::JniInterface<::dicekeys::App, NativeApp>;

};

}  // namespace djinni_generated
