// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ImageProcessor.djinni

#pragma once

#include "ImageProcessor.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeImageProcessor final : ::djinni::JniInterface<::dicekeys::ImageProcessor, NativeImageProcessor> {
public:
    using CppType = std::shared_ptr<::dicekeys::ImageProcessor>;
    using CppOptType = std::shared_ptr<::dicekeys::ImageProcessor>;
    using JniType = jobject;

    using Boxed = NativeImageProcessor;

    ~NativeImageProcessor();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeImageProcessor>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeImageProcessor>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeImageProcessor();
    friend ::djinni::JniClass<NativeImageProcessor>;
    friend ::djinni::JniInterface<::dicekeys::ImageProcessor, NativeImageProcessor>;

};

}  // namespace djinni_generated
