// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DiceKeyImageProcessorWrapper.djinni

#include "NativeDiceKeyImageProcessorWrapper.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeDiceKeyImageProcessorWrapper::NativeDiceKeyImageProcessorWrapper() : ::djinni::JniInterface<::dicekeys::DiceKeyImageProcessorWrapper, NativeDiceKeyImageProcessorWrapper>("com/dicekeys/dicekeys/DiceKeyImageProcessorWrapper$CppProxy") {}

NativeDiceKeyImageProcessorWrapper::~NativeDiceKeyImageProcessorWrapper() = default;


CJNIEXPORT void JNICALL Java_com_dicekeys_dicekeys_DiceKeyImageProcessorWrapper_00024CppProxy_nativeDestroy(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        delete reinterpret_cast<::djinni::CppProxyHandle<::dicekeys::DiceKeyImageProcessorWrapper>*>(nativeRef);
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, )
}

CJNIEXPORT jobject JNICALL Java_com_dicekeys_dicekeys_DiceKeyImageProcessorWrapper_00024CppProxy_create(JNIEnv* jniEnv, jobject /*this*/)
{
    try {
        DJINNI_FUNCTION_PROLOGUE0(jniEnv);
        auto r = ::dicekeys::DiceKeyImageProcessorWrapper::create();
        return ::djinni::release(::djinni_generated::NativeDiceKeyImageProcessorWrapper::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

CJNIEXPORT jstring JNICALL Java_com_dicekeys_dicekeys_DiceKeyImageProcessorWrapper_00024CppProxy_native_1getHelloWorld(JNIEnv* jniEnv, jobject /*this*/, jlong nativeRef)
{
    try {
        DJINNI_FUNCTION_PROLOGUE1(jniEnv, nativeRef);
        const auto& ref = ::djinni::objectFromHandleAddress<::dicekeys::DiceKeyImageProcessorWrapper>(nativeRef);
        auto r = ref->getHelloWorld();
        return ::djinni::release(::djinni::String::fromCpp(jniEnv, r));
    } JNI_TRANSLATE_EXCEPTIONS_RETURN(jniEnv, 0 /* value doesn't matter */)
}

}  // namespace djinni_generated
