disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - implicit_getter
  - line_length
  - type_body_length
  - type_name
  - weak_delegate
  - multiple_closures_with_trailing_closure
opt_in_rules:
  - closure_spacing
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
included: # paths to include during linting. `--path` is ignored if present.
  - DiceKeys
  - DiceKeysTests
  - DiceKeysUITests
excluded:
