// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from app.djinni

#import "DKApp+Private.h"
#import "DKApp.h"
#import "DJICppWrapperCache+Private.h"
#import "DJIError.h"
#import "DJIMarshal+Private.h"
#include <exception>
#include <stdexcept>
#include <utility>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@interface DKApp ()

- (id)initWithCpp:(const std::shared_ptr<::dicekeys::App>&)cppRef;

@end

@implementation DKApp {
    ::djinni::CppProxyCache::Handle<std::shared_ptr<::dicekeys::App>> _cppRefHandle;
}

- (id)initWithCpp:(const std::shared_ptr<::dicekeys::App>&)cppRef
{
    if (self = [super init]) {
        _cppRefHandle.assign(cppRef);
    }
    return self;
}

+ (nullable DKApp *)create {
    try {
        auto objcpp_result_ = ::dicekeys::App::create();
        return ::djinni_generated::App::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

- (nonnull NSString *)getHelloWorld {
    try {
        auto objcpp_result_ = _cppRefHandle.get()->getHelloWorld();
        return ::djinni::String::fromCpp(objcpp_result_);
    } DJINNI_TRANSLATE_EXCEPTIONS()
}

namespace djinni_generated {

auto App::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return objc->_cppRefHandle.get();
}

auto App::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return ::djinni::get_cpp_proxy<DKApp>(cpp);
}

}  // namespace djinni_generated

@end
