// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from app.djinni

#import <Foundation/Foundation.h>
@class DKApp;


@interface DKApp : NSObject

+ (nullable DKApp *)create;

- (nonnull NSString *)getHelloWorld;

@end
