// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from app.djinni

#include "App.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class DKApp;

namespace djinni_generated {

class App
{
public:
    using CppType = std::shared_ptr<::dicekeys::App>;
    using CppOptType = std::shared_ptr<::dicekeys::App>;
    using ObjcType = DKApp*;

    using Boxed = App;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

