// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DiceKeyImageProcessorWrapper.djinni

#import <Foundation/Foundation.h>
@class DKDiceKeyImageProcessorWrapper;


@interface DKDiceKeyImageProcessorWrapper : NSObject

/** `create()` factory method has to be used in Swift/Objective-C/Kotlin/Java */
+ (nullable DKDiceKeyImageProcessorWrapper *)create;

- (BOOL)processRGBAImage:(int32_t)width
                  height:(int32_t)height
                    data:(nonnull NSData *)data;

- (BOOL)processRGBAImageAndRenderOverlay:(int32_t)width
                                  height:(int32_t)height
                                    data:(nonnull NSData *)data;

- (BOOL)processAndAugmentRGBAImage:(int32_t)width
                            height:(int32_t)height
                              data:(nonnull NSData *)data;

- (nonnull NSString *)readJson;

- (BOOL)isFinished;

- (nonnull NSData *)getFaceImage:(int32_t)faceIndex
                          height:(int32_t)height
                            data:(nonnull NSData *)data;

@end
