// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DiceKeyImageProcessorWrapper.djinni

#import <Foundation/Foundation.h>
@class DKDiceKeyImageProcessorWrapper;


@interface DKDiceKeyImageProcessorWrapper : NSObject

/**
 * `create()` factory method has to be used to create an instance of the class in Swift/Objective-C/Kotlin/Java
 *
 * For example, in Swift:
 * let wrapper = DKDiceKeyImageProcessorWrapper.create()!
 *
 * in Objective-C:
 * DKDiceKeyImageProcessorWrapper *wrapper = [DKDiceKeyImageProcessorWrapper create];
 */
+ (nullable DKDiceKeyImageProcessorWrapper *)create;

- (BOOL)processRGBAImage:(int32_t)width
                  height:(int32_t)height
                    data:(nonnull NSData *)data;

- (BOOL)processRGBAImageAndRenderOverlay:(int32_t)width
                                  height:(int32_t)height
                                    data:(nonnull NSData *)data;

- (BOOL)processAndAugmentRGBAImage:(int32_t)width
                            height:(int32_t)height
                              data:(nonnull NSData *)data;

- (nonnull NSString *)readJson;

- (BOOL)isFinished;

- (nonnull NSData *)getFaceImage:(int32_t)faceIndex
                          height:(int32_t)height
                            data:(nonnull NSData *)data;

@end
