// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from DiceKeyImageProcessorWrapper.djinni

#pragma once

#include <memory>
#include <string>

namespace dicekeys {

class DiceKeyImageProcessorWrapper {
public:
    virtual ~DiceKeyImageProcessorWrapper() {}

    static std::shared_ptr<DiceKeyImageProcessorWrapper> create();

    virtual std::string getHelloWorld() = 0;
};

}  // namespace dicekeys
