// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

// DiceKeys_Bridging_Header.h
// DiceKeys_Bridging_Header

#import <Foundation/Foundation.h>

//! Project version number for DiceKeysBridgingHeader.
FOUNDATION_EXPORT double DiceKeysBridgingHeaderVersionNumber;

//! Project version string for DiceKeysBridgingHeader.
FOUNDATION_EXPORT const unsigned char DiceKeysBridgingHeaderVersionString[];

#import "DKImageProcessor.h"
