//
//  DerivationRecipeTemplates.swift
//  DiceKeys
//
//  Auto-generated by recipe.ts in the DiceKeys specification TypeScript project.
//  Tue, 12 Jan 2021 06:57:23 GMT
//
  
import Foundation

let derivationRecipeTemplates: [DerivationRecipeTemplate] = [
    DerivationRecipeTemplate(type: .Password, name: "1Password", derivationOptionsJson: """
{"allow":[{"host":"*.1password.com"}]}
"""),
    DerivationRecipeTemplate(type: .Password, name: "Apple", derivationOptionsJson: """
{"allow":[{"host":"*.apple.com"},{"host":"*.icloud.com"}],"lengthInChars":64}
"""),
    DerivationRecipeTemplate(type: .Password, name: "Authy", derivationOptionsJson: """
{"allow":[{"host":"*.authy.com"}]}
"""),
    DerivationRecipeTemplate(type: .Password, name: "Bitwarden", derivationOptionsJson: """
{"allow":[{"host":"*.bitwarden.com"}]}
"""),
    DerivationRecipeTemplate(type: .Password, name: "Facebook", derivationOptionsJson: """
{"allow":[{"host":"*.facebook.com"}]}
"""),
    DerivationRecipeTemplate(type: .Password, name: "Google", derivationOptionsJson: """
{"allow":[{"host":"*.google.com"}]}
"""),
    DerivationRecipeTemplate(type: .Password, name: "Keeper", derivationOptionsJson: """
{"allow":[{"host":"*.keepersecurity.com"},{"host":"*.keepersecurity.eu"}]}
"""),
    DerivationRecipeTemplate(type: .Password, name: "LastPass", derivationOptionsJson: """
{"allow":[{"host":"*.lastpass.com"}]}
"""),
    DerivationRecipeTemplate(type: .Password, name: "Microsoft", derivationOptionsJson: """
{"allow":[{"host":"*.microsoft.com"},{"host":"*.live.com"}]}
""")
];
