//////////////////////////////////////////////////////////
// DiceKeys Specification (NOT TO BE MODIFIED DIRECTLY!)
//////////////////////////////////////////////////////////
//
// This file specifies properties of DiceKey Faces,
// including:
//   -- The set of letters that uniquely identify each element
//      (such as a die or chip)
//   -- the set of digits (1-6) that identify the face of
//      each element
//   -- The encoding of bits into the underlines and overlines
//
// This file is generated automatically by the DiceKey
// specification generator, which is written in TypeScript.
// That program also generates:
//    -- The SVG file that renders the appearance of each face
//    -- The TypeScript version of this specification file
//
// To change the DiceKey specification, you will need to change
// and re-run specification program in TypeScript.
//
// To add additional definitions or help functions, create a new file
// that reads the constants you need from this file.
//

import Foundation
// SwiftUI required for CGFloat
import SwiftUI

enum FaceLetter: String, Codable, CaseIterable {
  case A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, R, S, T, U, V, W, X, Y, Z
}
let FaceLetters = Array(FaceLetter.allCases)

enum FaceDigit: String, Codable, CaseIterable {
  case _1 = "1"
  case _2 = "2"
  case _3 = "3"
  case _4 = "4"
  case _5 = "5"
  case _6 = "6"
}
let FaceDigits = Array(FaceDigit.allCases)

let faceLetterIndexes: [FaceLetter: UInt] = [
    FaceLetter.A: 0,
    FaceLetter.B: 1,
    FaceLetter.C: 2,
    FaceLetter.D: 3,
    FaceLetter.E: 4,
    FaceLetter.F: 5,
    FaceLetter.G: 6,
    FaceLetter.H: 7,
    FaceLetter.I: 8,
    FaceLetter.J: 9,
    FaceLetter.K: 10,
    FaceLetter.L: 11,
    FaceLetter.M: 12,
    FaceLetter.N: 13,
    FaceLetter.O: 14,
    FaceLetter.P: 15,
    FaceLetter.R: 16,
    FaceLetter.S: 17,
    FaceLetter.T: 18,
    FaceLetter.U: 19,
    FaceLetter.V: 20,
    FaceLetter.W: 21,
    FaceLetter.X: 22,
    FaceLetter.Y: 23,
    FaceLetter.Z: 24
]

let faceDigitIndexes: [FaceDigit: UInt8] = [
    FaceDigit._1: 0,
    FaceDigit._2: 1,
    FaceDigit._3: 2,
    FaceDigit._4: 3,
    FaceDigit._5: 4,
    FaceDigit._6: 5
]

let faceDigitValues: [FaceDigit: UInt8] = [
    FaceDigit._1: 1,
    FaceDigit._2: 2,
    FaceDigit._3: 3,
    FaceDigit._4: 4,
    FaceDigit._5: 5,
    FaceDigit._6: 6
]

enum FaceOrientationLetterTrbl: String, Codable, CaseIterable {
  case Top = "t"
  case Right = "r"
  case Bottom = "b"
  case Left = "l"
}
let FaceOrientationLettersTrbl = Array(FaceOrientationLetterTrbl.allCases)

let NumberOfDotsInUndoverline: Int = 11
let MinNumberOfBlackDotsInUndoverline: Int = 4
let MinNumberOfWhiteDotsInUndoverline: Int = 4

struct FaceWithUnderlineAndOverlineCode {
  let letter: FaceLetter
  let digit: FaceDigit
  let underlineCode: UInt8
  let overlineCode: UInt8
}

class FaceDimensionsFractional {
    static let size: CGFloat = 1
    static let margin: CGFloat = 0
    static let linearSizeOfFace: CGFloat = 1
    static let linearSizeOfFacesPrintArea: CGFloat = 1
    static let center: CGFloat = 0.5
    static let fontSize: CGFloat = 0.741935
    static let undoverlineLength: CGFloat = 1
    static let undoverlineThickness: CGFloat = 0.177419
    static let overlineTop: CGFloat = 0
    static let overlineBottom: CGFloat = 0.177419
    static let underlineBottom: CGFloat = 1
    static let underlineTop: CGFloat = 0.822581
    static let undoverlineMarginAtLineStartAndEnd: CGFloat = 0.056452
    static let undoverlineMarginAlongLength: CGFloat = 0.048387
    static let undoverlineLeftEdge: CGFloat = 0
    static let undoverlineFirstDotLeftEdge: CGFloat = 0.056452
    static let undoverlineDotWidth: CGFloat = 0.080645
    static let undoverlineDotHeight: CGFloat = 0.080645
    static let centerOfUndoverlineToCenterOfFace: CGFloat = 0.41129
    static let underlineDotTop: CGFloat = 0.870968
    static let overlineDotTop: CGFloat = 0.048387
    static let textBaselineY: CGFloat = 0.725806
    static let charWidth: CGFloat = 0.370968
    static let charHeight: CGFloat = 0.488194
    static let spaceBetweenLetterAndDigit: CGFloat = 0.04375
    static let textRegionWidth: CGFloat = 0.785685
    static let textRegionHeight: CGFloat = 0.488194
    static let dotCentersAsFractionOfUndoverline: [CGFloat] = [0.0967745, 0.1774195, 0.2580645, 0.3387095, 0.41935449999999996, 0.4999995, 0.5806445, 0.6612894999999999, 0.7419344999999999, 0.8225795, 0.9032244999999999]
}

let letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes: [FaceWithUnderlineAndOverlineCode] = [
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.A, digit: FaceDigit._1, underlineCode: 7, overlineCode: 233),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.A, digit: FaceDigit._2, underlineCode: 11, overlineCode: 241),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.A, digit: FaceDigit._3, underlineCode: 13, overlineCode: 224),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.A, digit: FaceDigit._4, underlineCode: 22, overlineCode: 242),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.A, digit: FaceDigit._5, underlineCode: 26, overlineCode: 234),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.A, digit: FaceDigit._6, underlineCode: 30, overlineCode: 225),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.B, digit: FaceDigit._1, underlineCode: 31, overlineCode: 230),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.B, digit: FaceDigit._2, underlineCode: 38, overlineCode: 195),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.B, digit: FaceDigit._3, underlineCode: 39, overlineCode: 196),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.B, digit: FaceDigit._4, underlineCode: 41, overlineCode: 198),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.B, digit: FaceDigit._5, underlineCode: 43, overlineCode: 220),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.B, digit: FaceDigit._6, underlineCode: 44, overlineCode: 202),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.C, digit: FaceDigit._1, underlineCode: 45, overlineCode: 205),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.C, digit: FaceDigit._2, underlineCode: 46, overlineCode: 208),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.C, digit: FaceDigit._3, underlineCode: 49, overlineCode: 201),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.C, digit: FaceDigit._4, underlineCode: 50, overlineCode: 212),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.C, digit: FaceDigit._5, underlineCode: 51, overlineCode: 211),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.C, digit: FaceDigit._6, underlineCode: 52, overlineCode: 197),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.D, digit: FaceDigit._1, underlineCode: 53, overlineCode: 194),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.D, digit: FaceDigit._2, underlineCode: 55, overlineCode: 216),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.D, digit: FaceDigit._3, underlineCode: 57, overlineCode: 218),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.D, digit: FaceDigit._4, underlineCode: 58, overlineCode: 199),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.D, digit: FaceDigit._5, underlineCode: 59, overlineCode: 192),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.D, digit: FaceDigit._6, underlineCode: 60, overlineCode: 214),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.E, digit: FaceDigit._1, underlineCode: 61, overlineCode: 209),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.E, digit: FaceDigit._2, underlineCode: 62, overlineCode: 204),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.E, digit: FaceDigit._3, underlineCode: 63, overlineCode: 203),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.E, digit: FaceDigit._4, underlineCode: 69, overlineCode: 166),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.E, digit: FaceDigit._5, underlineCode: 71, overlineCode: 188),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.E, digit: FaceDigit._6, underlineCode: 74, overlineCode: 163),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.F, digit: FaceDigit._1, underlineCode: 75, overlineCode: 164),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.F, digit: FaceDigit._2, underlineCode: 76, overlineCode: 178),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.F, digit: FaceDigit._3, underlineCode: 77, overlineCode: 181),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.F, digit: FaceDigit._4, underlineCode: 78, overlineCode: 168),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.F, digit: FaceDigit._5, underlineCode: 81, overlineCode: 177),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.F, digit: FaceDigit._6, underlineCode: 82, overlineCode: 172),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.G, digit: FaceDigit._1, underlineCode: 83, overlineCode: 171),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.G, digit: FaceDigit._2, underlineCode: 85, overlineCode: 186),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.G, digit: FaceDigit._3, underlineCode: 86, overlineCode: 167),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.G, digit: FaceDigit._4, underlineCode: 87, overlineCode: 160),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.G, digit: FaceDigit._5, underlineCode: 88, overlineCode: 165),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.G, digit: FaceDigit._6, underlineCode: 89, overlineCode: 162),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.H, digit: FaceDigit._1, underlineCode: 91, overlineCode: 184),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.H, digit: FaceDigit._2, underlineCode: 92, overlineCode: 174),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.H, digit: FaceDigit._3, underlineCode: 93, overlineCode: 169),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.H, digit: FaceDigit._4, underlineCode: 94, overlineCode: 180),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.H, digit: FaceDigit._5, underlineCode: 95, overlineCode: 179),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.H, digit: FaceDigit._6, underlineCode: 98, overlineCode: 157),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.I, digit: FaceDigit._1, underlineCode: 99, overlineCode: 154),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.I, digit: FaceDigit._2, underlineCode: 100, overlineCode: 140),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.I, digit: FaceDigit._3, underlineCode: 101, overlineCode: 139),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.I, digit: FaceDigit._4, underlineCode: 102, overlineCode: 150),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.I, digit: FaceDigit._5, underlineCode: 103, overlineCode: 145),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.I, digit: FaceDigit._6, underlineCode: 104, overlineCode: 148),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.J, digit: FaceDigit._1, underlineCode: 105, overlineCode: 147),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.J, digit: FaceDigit._2, underlineCode: 106, overlineCode: 142),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.J, digit: FaceDigit._3, underlineCode: 107, overlineCode: 137),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.J, digit: FaceDigit._4, underlineCode: 109, overlineCode: 152),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.J, digit: FaceDigit._5, underlineCode: 110, overlineCode: 133),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.J, digit: FaceDigit._6, underlineCode: 111, overlineCode: 130),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.K, digit: FaceDigit._1, underlineCode: 112, overlineCode: 155),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.K, digit: FaceDigit._2, underlineCode: 113, overlineCode: 156),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.K, digit: FaceDigit._3, underlineCode: 114, overlineCode: 129),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.K, digit: FaceDigit._4, underlineCode: 115, overlineCode: 134),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.K, digit: FaceDigit._5, underlineCode: 116, overlineCode: 144),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.K, digit: FaceDigit._6, underlineCode: 117, overlineCode: 151),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.L, digit: FaceDigit._1, underlineCode: 118, overlineCode: 138),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.L, digit: FaceDigit._2, underlineCode: 119, overlineCode: 141),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.L, digit: FaceDigit._3, underlineCode: 120, overlineCode: 136),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.L, digit: FaceDigit._4, underlineCode: 121, overlineCode: 143),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.L, digit: FaceDigit._5, underlineCode: 122, overlineCode: 146),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.L, digit: FaceDigit._6, underlineCode: 123, overlineCode: 149),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.M, digit: FaceDigit._1, underlineCode: 124, overlineCode: 131),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.M, digit: FaceDigit._2, underlineCode: 125, overlineCode: 132),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.M, digit: FaceDigit._3, underlineCode: 126, overlineCode: 153),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.M, digit: FaceDigit._4, underlineCode: 133, overlineCode: 106),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.M, digit: FaceDigit._5, underlineCode: 135, overlineCode: 112),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.M, digit: FaceDigit._6, underlineCode: 137, overlineCode: 114),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.N, digit: FaceDigit._1, underlineCode: 139, overlineCode: 104),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.N, digit: FaceDigit._2, underlineCode: 141, overlineCode: 121),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.N, digit: FaceDigit._3, underlineCode: 142, overlineCode: 100),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.N, digit: FaceDigit._4, underlineCode: 143, overlineCode: 99),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.N, digit: FaceDigit._5, underlineCode: 146, overlineCode: 96),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.N, digit: FaceDigit._6, underlineCode: 147, overlineCode: 103),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.O, digit: FaceDigit._1, underlineCode: 148, overlineCode: 113),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.O, digit: FaceDigit._2, underlineCode: 149, overlineCode: 118),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.O, digit: FaceDigit._3, underlineCode: 150, overlineCode: 107),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.O, digit: FaceDigit._4, underlineCode: 151, overlineCode: 108),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.O, digit: FaceDigit._5, underlineCode: 152, overlineCode: 105),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.O, digit: FaceDigit._6, underlineCode: 153, overlineCode: 110),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.P, digit: FaceDigit._1, underlineCode: 154, overlineCode: 115),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.P, digit: FaceDigit._2, underlineCode: 155, overlineCode: 116),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.P, digit: FaceDigit._3, underlineCode: 156, overlineCode: 98),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.P, digit: FaceDigit._4, underlineCode: 157, overlineCode: 101),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.P, digit: FaceDigit._5, underlineCode: 158, overlineCode: 120),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.P, digit: FaceDigit._6, underlineCode: 161, overlineCode: 76),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.R, digit: FaceDigit._1, underlineCode: 162, overlineCode: 81),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.R, digit: FaceDigit._2, underlineCode: 163, overlineCode: 86),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.R, digit: FaceDigit._3, underlineCode: 165, overlineCode: 71),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.R, digit: FaceDigit._4, underlineCode: 166, overlineCode: 90),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.R, digit: FaceDigit._5, underlineCode: 167, overlineCode: 93),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.R, digit: FaceDigit._6, underlineCode: 168, overlineCode: 88),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.S, digit: FaceDigit._1, underlineCode: 170, overlineCode: 66),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.S, digit: FaceDigit._2, underlineCode: 171, overlineCode: 69),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.S, digit: FaceDigit._3, underlineCode: 172, overlineCode: 83),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.S, digit: FaceDigit._4, underlineCode: 173, overlineCode: 84),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.S, digit: FaceDigit._5, underlineCode: 174, overlineCode: 73),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.S, digit: FaceDigit._6, underlineCode: 175, overlineCode: 78),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.T, digit: FaceDigit._1, underlineCode: 176, overlineCode: 87),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.T, digit: FaceDigit._2, underlineCode: 177, overlineCode: 80),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.T, digit: FaceDigit._3, underlineCode: 178, overlineCode: 77),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.T, digit: FaceDigit._4, underlineCode: 179, overlineCode: 74),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.T, digit: FaceDigit._5, underlineCode: 180, overlineCode: 92),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.T, digit: FaceDigit._6, underlineCode: 181, overlineCode: 91),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.U, digit: FaceDigit._1, underlineCode: 182, overlineCode: 70),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.U, digit: FaceDigit._2, underlineCode: 183, overlineCode: 65),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.U, digit: FaceDigit._3, underlineCode: 184, overlineCode: 68),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.U, digit: FaceDigit._4, underlineCode: 185, overlineCode: 67),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.U, digit: FaceDigit._5, underlineCode: 186, overlineCode: 94),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.U, digit: FaceDigit._6, underlineCode: 187, overlineCode: 89),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.V, digit: FaceDigit._1, underlineCode: 188, overlineCode: 79),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.V, digit: FaceDigit._2, underlineCode: 189, overlineCode: 72),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.V, digit: FaceDigit._3, underlineCode: 190, overlineCode: 85),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.V, digit: FaceDigit._4, underlineCode: 193, overlineCode: 52),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.V, digit: FaceDigit._5, underlineCode: 194, overlineCode: 41),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.V, digit: FaceDigit._6, underlineCode: 195, overlineCode: 46),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.W, digit: FaceDigit._1, underlineCode: 196, overlineCode: 56),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.W, digit: FaceDigit._2, underlineCode: 198, overlineCode: 34),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.W, digit: FaceDigit._3, underlineCode: 199, overlineCode: 37),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.W, digit: FaceDigit._4, underlineCode: 201, overlineCode: 39),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.W, digit: FaceDigit._5, underlineCode: 202, overlineCode: 58),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.W, digit: FaceDigit._6, underlineCode: 203, overlineCode: 61),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.X, digit: FaceDigit._1, underlineCode: 204, overlineCode: 43),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.X, digit: FaceDigit._2, underlineCode: 205, overlineCode: 44),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.X, digit: FaceDigit._3, underlineCode: 206, overlineCode: 49),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.X, digit: FaceDigit._4, underlineCode: 207, overlineCode: 54),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.X, digit: FaceDigit._5, underlineCode: 208, overlineCode: 47),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.X, digit: FaceDigit._6, underlineCode: 209, overlineCode: 40),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Y, digit: FaceDigit._1, underlineCode: 210, overlineCode: 53),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Y, digit: FaceDigit._2, underlineCode: 211, overlineCode: 50),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Y, digit: FaceDigit._3, underlineCode: 212, overlineCode: 36),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Y, digit: FaceDigit._4, underlineCode: 213, overlineCode: 35),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Y, digit: FaceDigit._5, underlineCode: 214, overlineCode: 62),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Y, digit: FaceDigit._6, underlineCode: 215, overlineCode: 57),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Z, digit: FaceDigit._1, underlineCode: 216, overlineCode: 60),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Z, digit: FaceDigit._2, underlineCode: 217, overlineCode: 59),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Z, digit: FaceDigit._3, underlineCode: 218, overlineCode: 38),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Z, digit: FaceDigit._4, underlineCode: 219, overlineCode: 33),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Z, digit: FaceDigit._5, underlineCode: 220, overlineCode: 55),
    FaceWithUnderlineAndOverlineCode(letter: FaceLetter.Z, digit: FaceDigit._6, underlineCode: 221, overlineCode: 48)
]

let underlineCodeToFaceWithUnderlineAndOverlineCode: [FaceWithUnderlineAndOverlineCode?] = [
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[0],
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[1],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[2],
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[3],
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[4],
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[5],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[6],
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[7],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[8],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[9],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[10],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[11],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[12],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[13],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[14],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[15],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[16],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[17],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[18],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[19],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[20],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[21],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[22],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[23],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[24],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[25],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[26],
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[27],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[28],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[29],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[30],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[31],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[32],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[33],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[34],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[35],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[36],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[37],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[38],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[39],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[40],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[41],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[42],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[43],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[44],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[45],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[46],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[47],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[48],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[49],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[50],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[51],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[52],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[53],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[54],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[55],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[56],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[57],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[58],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[59],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[60],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[61],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[62],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[63],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[64],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[65],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[66],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[67],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[68],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[69],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[70],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[71],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[72],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[73],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[74],
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[75],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[76],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[77],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[78],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[79],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[80],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[81],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[82],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[83],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[84],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[85],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[86],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[87],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[88],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[89],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[90],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[91],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[92],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[93],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[94],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[95],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[96],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[97],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[98],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[99],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[100],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[101],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[102],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[103],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[104],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[105],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[106],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[107],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[108],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[109],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[110],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[111],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[112],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[113],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[114],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[115],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[116],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[117],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[118],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[119],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[120],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[121],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[122],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[123],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[124],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[125],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[126],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[127],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[128],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[129],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[130],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[131],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[132],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[133],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[134],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[135],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[136],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[137],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[138],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[139],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[140],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[141],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[142],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[143],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[144],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[145],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[146],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[147],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[148],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[149],
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil
]

let overlineCodeToFaceWithUnderlineAndOverlineCode: [FaceWithUnderlineAndOverlineCode?] = [
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[147],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[127],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[141],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[140],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[128],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[146],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[129],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[137],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[124],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[132],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[133],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[125],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[136],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[149],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[134],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[139],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[123],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[138],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[135],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[148],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[126],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[143],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[130],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[145],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[144],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[131],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[142],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[115],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[102],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[117],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[116],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[103],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[114],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[98],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[121],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[106],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[111],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[95],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[110],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[107],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[120],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[109],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[96],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[104],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[105],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[122],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[97],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[108],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[101],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[119],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[99],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[113],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[112],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[100],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[118],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[82],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[92],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[81],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[80],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[93],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[83],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[78],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[88],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[75],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[86],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[87],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[89],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[76],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[84],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[77],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[90],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[91],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[85],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[94],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[79],
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[62],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[59],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[72],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[73],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[58],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[63],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[68],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[56],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[66],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[50],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[49],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[67],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[55],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[69],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[64],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[52],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[70],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[54],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[53],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[71],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[51],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[65],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[57],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[74],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[48],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[60],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[61],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[47],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[39],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[41],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[29],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[30],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[40],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[27],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[38],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[33],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[44],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[36],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[35],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[43],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[34],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[31],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[46],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[45],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[32],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[42],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[37],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[28],
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[22],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[18],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[7],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[8],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[17],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[9],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[21],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[14],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[11],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[26],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[25],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[12],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[13],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[24],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[16],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[15],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[23],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[19],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[20],
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[10],
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[2],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[5],
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[6],
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[0],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[4],
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[1],
    letterIndexTimesSixPlusDigitIndexFaceWithUndoverlineCodes[3],
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil,
    nil
]
