name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: recursive
      - name: Build workspace
        run: |
          pod install
          xcrun simctl list
          xcodebuild clean test -workspace "DiceKeys.xcworkspace" -scheme 'DiceKeys' -destination 'platform=iOS Simulator,name=iPhone 12'  
